name: QA - Ranking (Prod)

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL of deployed site"
        required: false
        default: "https://ashtanga-yoga-quiz.onrender.com"
  push:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps (ci or install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Ensure Puppeteer is installed
        run: |
          node -e "try{console.log('puppeteer',require('puppeteer/package.json').version)}catch(e){process.exit(1)}" \
          || npm i -D puppeteer
          node -e "console.log('puppeteer',require('puppeteer/package.json').version)"

      - name: Run headless QA
        run: |
          set -o pipefail
          BASE="${{ inputs.base_url }}"
          if [ -z "$BASE" ]; then BASE="https://ashtanga-yoga-quiz.onrender.com"; fi
          export BASE_URL="$BASE"
          echo "BASE=$BASE_URL"
          node qa/check-ranking.mjs 2>&1 | tee qa_output.txt

      - name: Append QA logs to Summary
        if: always()
        run: |
          echo '### QA Output' >> $GITHUB_STEP_SUMMARY
          if [ -f qa_output.txt ]; then
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -n 1000 qa_output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo '(qa_output.txt missing)' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload QA artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa_output
          path: qa_output.txt
          if-no-files-found: warn
