name: QA - Ranking (Prod)

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL to test'
        required: false
        default: https://ashtanga-yoga-quiz.onrender.com
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (ci or install)
        run: |
          npm ci || npm install

      - name: Ensure Puppeteer is installed
        run: |
          npm ls puppeteer || npm i -D puppeteer@22

      - name: Run headless QA
        env:
          BASE_URL: ${{ inputs.base_url || 'https://ashtanga-yoga-quiz.onrender.com' }}
        run: |
          set -e
          node qa/check-ranking.mjs | tee qa_output.txt

      - name: Append QA logs to Summary
        if: always()
        run: |
          echo '## QA Output' >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          if [ -f qa_output.txt ]; then cat qa_output.txt >> $GITHUB_STEP_SUMMARY; else echo '(qa_output.txt missing)' >> $GITHUB_STEP_SUMMARY; fi
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Publish QA logs into repo (qa-reports/)
        if: always()
        run: |
          mkdir -p qa-reports
          if [ -f qa_output.txt ]; then
            cp qa_output.txt "qa-reports/qa_${{ github.run_id }}.txt"
          else
            echo "(qa_output.txt missing)" > "qa-reports/qa_${{ github.run_id }}.txt"
          fi

      - name: Commit QA log file
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          add: 'qa-reports/qa_${{ github.run_id }}.txt'
          message: 'chore(qa): add run ${{ github.run_id }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload QA artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa_output
          path: qa_output.txt
          if-no-files-found: warn
